name: build exe 

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: windows-latest
    steps:
#     拉取代码
    - uses: actions/checkout@v2
#     拉取flutter
    - uses: subosito/flutter-action@v1
      with:
        channel: beta
    - run: flutter config --enable-windows-desktop
    - name: Build release 
      run: |
        flutter packages get	
        flutter build -v windows --release
      working-directory: ${{env.GITHUB_WORKSPACE}}/
